Added nodejs - getting-started
MoralisWeb3/MoralisDocumentation pull request #74
Opened 2022-03-11 09:53 UTC by dhaileytaha

2022-03-11 14:10 UTC, YosephKS requested changes
Make some changes here 🙌🏼 

also is there any reason why we build servers here? seems a bit advanced for getting started

I think going with a single-file node script is enough

2022-03-11 14:10 UTC, YosephKS commented on SUMMARY.md
> +  * [Connect using Node.js](moralis-server/getting-started/connect-using-node.md)
Add an emoji here

2022-03-11 14:10 UTC, YosephKS commented on moralis-server/connect-the-sdk/connect-using-node.md
> +## Adding Moralis to Your Web Page using Node.js
Not Web page, this might be better

```suggestion
## Adding Moralis to Node.js
```

2022-03-11 14:10 UTC, YosephKS commented on moralis-server/connect-the-sdk/connect-using-node.md
> +    const web3 = await Moralis.enableWeb3({ privateKey: "YOUR-PRIVATE-KEY" });
Let's make this `web3Provider` instead, so devs don't confuse we're using web3js by default

2022-03-14 02:00 UTC, dhaileytaha commented on SUMMARY.md
> +  * [Connect using Node.js](moralis-server/getting-started/connect-using-node.md)
i will leave this to you

2022-03-14 02:02 UTC, dhaileytaha commented on moralis-server/connect-the-sdk/connect-using-node.md
> +    await Moralis.start({ serverUrl, appId, masterKey, moralisSecret });
resolved

2022-03-14 02:02 UTC, dhaileytaha commented on moralis-server/connect-the-sdk/connect-using-node.md
> +    const web3 = await Moralis.enableWeb3({ privateKey: "YOUR-PRIVATE-KEY" });
done

2022-03-17 08:21 UTC, YosephKS approved these changes

2022-03-17 08:21 UTC, merged